sudo: required
services:
- docker

# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial
env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - secure: "P5VlYMgfNy0ukdU1S6l4jBZBNZSqMALpV1a+GiS9AhRhlejn093hQ/8oFbH/Lf1WenFf3fYJ34+7EyFK/3GnX9S6lP+5u2ocCIQXwNkCE+NeaXsz+I1wwuxzVOoKgIKLttmo+jt4O1BOy9SW2afH1uwvgUZbQKy2UYjtpvJNWcrCXPhJoHdh2R3XjKotCdBNoRevM2htdbnygLASkiyHxWCgHCY6EiJb7noF9ZZ1S3EPxy1tSDmCsnpPv/15LqpVbZoklnZbzyUliSI4yePLJ2v0SGGtPUj6k8NkkhcK0ZJXbdV933Qu6oF0TTml1t8O5+8EX2ulabJh9CMNfd8dF0LVjd5D4OV3MWRE0TvWSfdqJxK/feUBs13YyPAA2lOEiNIHmJiHKn+m78n5R8ohKKqcF6J8/kq7vRxuI+srmGiSVv5/wESRZKlVReEzWIFoAsMahqGIdQSjdC67uumZ1gnDDK6IpqoPzhdMEkc5umcSrWgIZ4c4pLFga4N/FY1N1OLImEgJDokdKyNPMSQRoc3ne95HXiY54EfpfrIaCKYhqOoLTVe8FdXgaUFXz9sE5nDvjzHwC0xcrzWwD+RyZYaB5G2+QYBPNqJxCOT8X2MkqclBNC7l2V/ZkH3dX0taNUL6vzAjk/qDk8nIx7+r2gXCo2EMrBoCy/U3JsjgglY="
    - secure: "ITURXRTzpvBwNkHGWESHyY53JIytJoQxKkMqIbUwx1R7u6+f4OEuSqAAIyn5GElzQcdTV35OlYt8KfV8N/doCmk58YtE7N3B7DPk1abo854XhNC1Vof7nzaDSCLkZvgSrHc04v7b2a8t5S/wOZIt/aTNLphfW/IiiNwWPKU8mr+8O41VFXfVsBx8g1XYE2VbB3HJySYsFkDjfICtxYWIajnRZerchspXVND98o1naJpNgKBWVClmNSH1+8cwl2zsnJdfvyepKCZ7IliXMj5CR2+o1T+r32BEAYfZuKd83MjZdkKok3Psq4RmUVwJdPuo3tdMFWEHtvq5Tbkq9nqpirH2r6x6eX1Xmxyo4suVJS6zqxyrL6sThMWECwucQSK0IVnJOWaJgJmKduO4gdXn1ln5VtheUBo71iokl5Q2GJ5v4CxP4yxpyHpP4NxGFuLZ9kkz7GBVOQJMVJilo3Mho7PrLOzFmtGZk/0MKy6lpwzPohws85qmaGgs8sBbMXnccRKQDZYsmqwxviouHhp9wQ1EZ8pJ+OKBmmL0Z1G58D0Yehon0QrBHw0nZmhNGlh1l7iMRnow4Mh/9DLVEi3JXK1gCMMPTG79rpwdo2kvptKLQyp/6Lb5uCtJ9g6ckBAOHx5uLeHg0veoAOv1zU8Ekbk6jEsN6tUQVrcvm9EjlMo="

install:
  # Install bash_unit for testing
  - curl -o bash_unit "https://raw.githubusercontent.com/pgrange/bash_unit/master/bash_unit"
  - chmod +x bash_unit
  # Download kubectl, which is a requirement for using minikube.
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  # Download minikube.
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.35.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - mkdir -p $HOME/.kube $HOME/.minikube
  - touch $KUBECONFIG
  - sudo minikube start --vm-driver=none --kubernetes-version=v1.13.0
  - "sudo chown -R travis: /home/travis/.minikube/"

before_script:
  # Following is just to demo that the kubernetes cluster works.
  - kubectl cluster-info
  # Verify kube-addon-manager.
  # kube-addon-manager is responsible for managing other kubernetes components, such as kube-dns, dashboard, storage-provisioner..
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lcomponent=kube-addon-manager -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-addon-manager to be available"; kubectl get pods --all-namespaces; done
  # Wait for kube-dns to be ready.
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-dns to be available"; kubectl get pods --all-namespaces; done

script:
  - make test
  - kubectl apply -f tests/kubernetes-role-access.yaml
  - ./bash_unit tests/test_*

before_deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"

deploy:
  # push taged container to docker hub
  - provider: script
    script: make push
    on:
      branch: master
#      tags: true
