---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: travis-example
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 60']
  initContainers:
  - name: init-mydb
    image: dcasavant/k8s-wait-for:test
    env:
    - name: job
      value: "pi"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
